cache-dir = "/root/venv"
installer.parallel = false
installer.max-workers = 16
virtualenvs.create = true
virtualenvs.options.always-copy = false
virtualenvs.prompt = "{project_name}-py{python_version}"